# Generated by Django 5.1 on 2024-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('validade', models.DateField(null=True)),
                ('quantidade', models.CharField(max_length=50)),
                ('disponivel', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('marca', models.CharField(max_length=50, null=True)),
                ('estado_de_uso', models.CharField(max_length=50)),
                ('imagem', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
