# Generated by Django 5.1.2 on 2025-01-24 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.campus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.campus'),
        ),
    ]
