# Generated by Django 5.1.2 on 2025-01-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_campus_inventario_campus_alter_usuario_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ingresso',
            field=models.CharField(default=2022.0, max_length=15),
            preserve_default=False,
        ),
    ]
