# Generated by Django 5.1.2 on 2025-02-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.categoria'),
            preserve_default=False,
        ),
    ]
