# Generated by Django 5.1.2 on 2025-02-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_solicitacao_avaliador'),
        ('inventario', '0007_inventario_categoria'),
    ]

    operations = [
    ]
