# Generated by Django 5.1.2 on 2025-02-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_merge_20250211_0948'),
        ('inventario', '0008_merge_20250218_0734'),
    ]

    operations = [
    ]
