# Generated by Django 5.1.2 on 2025-02-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_merge_20250225_0725'),
        ('inventario', '0009_merge_20250225_0759'),
    ]

    operations = [
    ]
